name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CI: true

    runs-on: ${{ matrix.os }}

    # TODO: enable builds on Windows
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Git for committing
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "gh-actions@domain"
    - run: npm ci
      name: Run NPM clean install
    - name: Run tests
      shell: pwsh
      run: ./test/GitInfoTest.ps1
